export const productConstants = {
  GETCATEGORY_REQUEST: "GETCATEGORY_REQUEST",
  GETCATEGORY_SUCCESS: "GETCATEGORY_SUCCESS",
  GETCATEGORY_FAILURE: "GETCATEGORY_FAILURE",

  GETPRODUCT_REQUEST: "GETPRODUCT_REQUEST",
  GETPRODUCT_SUCCESS: "GETPRODUCT_SUCCESS",
  GETPRODUCT_FAILURE: "GETPRODUCT_FAILURE",
};

export const cartConstants = {
  MANAGE_CART_STATE: "MANAGE_CART_STATE",
};

export const orderConstants = {
  GETORDER_REQUEST: "GETORDER_REQUEST",
  GETORDER_SUCCESS: "GETORDER_SUCCESS",
  GETORDER_FAILURE: "GETORDER_FAILURE",

  PLACEORDER_REQUEST: "PLACEORDER_REQUEST",
  PLACEORDER_SUCCESS: "PLACEORDER_SUCCESS",
  PLACEORDER_FAILURE: "PLACEORDER_FAILURE",
};
