export const productConstants = {
  GETCATEGORY_REQUEST: "GETCATEGORY_REQUEST",
  GETCATEGORY_SUCCESS: "GETCATEGORY_SUCCESS",
  GETCATEGORY_FAILURE: "GETCATEGORY_FAILURE",

  GETPRODUCT_REQUEST: "GETPRODUCT_REQUEST",
  GETPRODUCT_SUCCESS: "GETPRODUCT_SUCCESS",
  GETPRODUCT_FAILURE: "GETPRODUCT_FAILURE",
};

export const cartConstants = {
  ADDTOCART_SUCCESS: "ADDTOCART_SUCCESS",
};
